### ISSUE TITLE
pre-load messages on user login

### ISSUE THREAD

**Issue by ChetanKhanna** [PS-Division-BITS/Chat#7]
@ritiktaneja 
We need to have some definite number of messages pre-loaded when the users logs in. So maybe an endpoint for fetching last 'n' messages would be good? When the client receives the user authenticated response, it could then go and load those messages from that end point.

**Comment by ritiktaneja** [comment]
Yeah fine for me, client can even send request to load more data.
Refer DRF's pages documentation.

**Comment by ChetanKhanna** [comment]
closed with 4680ad3eb04de73708223c3b0dcb2783cca299ad
